export const skills = [
  { name: "Html", level: 98 },
  { name: "Css", level: 98 },
  { name: "Javascript", level: 95 },
  { name: "React", level: 95 },
  { name: "Redux", level: 80 },
  { name: "Next js", level: 70 },
  { name: "Tailwind", level: 90 },
  { name: "TypeScript", level: 90 },
  { name: "Angular", level: 85 },
  { name: "Rxjs", level: 70 },
  { name: "Tanstack", level: 70 },
  { name: "Git", level: 80 },
  { name: "Github", level: 80 },
  { name: "Github Copilot", level: 60 },
  { name: "Node.js", level: 50 },
  { name: "MongoDB", level: 50 },
  { name: "SQL", level: 50 },
  { name: "Postgres SQL", level: 50 },
];
